apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.image.repository }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: REACT_APP_BACKEND_URL
          value: "http://{{ .Values.backendService.name }}:{{ .Values.backendService.port }}/api"
