name: Terraform Apply

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        
      - name: Get RDS Endpoint
        id: rds_endpoint
        run: echo "::set-output name=db_endpoint::$(terraform output -raw rds_endpoint)"

      - name: Wait for RDS to be available
        run: |
          until nc -zv ${{ steps.rds_endpoint.outputs.db_endpoint }} 5432; do
            echo "Waiting for RDS database to be ready..."
            sleep 10
          done

      - name: Load SQL dump into PostgreSQL
        run: |
          PGPASSWORD=${{ secrets.DB_PASSWORD }} psql -h ${{ steps.rds_endpoint.outputs.db_endpoint }} -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -f ./data/data.sql



          
